#!/usr/bin/env bash

SOURCE="https://github.com/kkiani/ShannonHome"

echo "------- Shannon Home Automation platform (2.0) ------ "
echo "- copyright ~> Kiarash Kiani                        - "
echo "- email     ~> kiani@kiarash.info                   - "
echo "- repo      ~> ${SOURCE} - "
echo "----------------------------------------------------- "

function run {
    status "[*] running services."
    sudo nohup python3 -m packages.services.hws.hardware_service &
    sudo nohup python3 -m packages.services.server.app &
}

function cleanSystem {
    status "[*] clear cache file system."
    sudo rm -R /pid/*
    rm -r nohup.out
}

function update {
    status "[*] pull updates from source."
    git clean -df
    git checkout -- .
    git pull origin master
}

function status {
    COLOR='\033[1;33m'
    NC='\033[0m'

    echo -e "${COLOR}$1${NC}"
}

cleanSystem
update
run